[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@superfluid-finance/metadata/src/=node_modules\@superfluid-finance\metadata',
    '@superfluid-finance/ethereum-contracts/=node_modules/@superfluid-finance/ethereum-contracts/'
    ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
